title: ENKA Electronics
description: ENKA Electronics - ხარისხიანი ტექნიკა საქართველოში უფასო მიტანით და ადგილზე გადახდით.

url: "enkaelectronics.com.ge"   # 👈 твой кастомный домен
baseurl: ""
encoding: utf-8
facebook_pixel_id: "1499689204986172"

# Исключаем лишние папки
exclude:
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock
  - README.md
  - generate_pages.js
  - .github
  - .gitignore
  - .git
  - .bundle

# Коллекция товаров
collections:
  products:
    output: true
    permalink: /:collection/:path/

# Настройки по умолчанию для товаров
defaults:
  - scope:
      path: "_products/*.md"
    values:
      layout: "product"
      permalink: /:title/

# Плагины (стандартные для GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Настройки для sitemap
sitemap:
  filename: sitemap.xml

# Локализация
lang: "ka"
locale: "ka_GE"
