title: ENKA Electronics
description: ENKA Electronics - ხარისხიანი ტექნიკა საქართველოში უფასო მიტანით და ადგილზე გადახდით.

url: "enkaelectronics.com.ge"   # 👈 твой кастомный домен
baseurl: ""
encoding: utf-8
facebook_pixel_id: "1499689204986172"

exclude:
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock
  - README.md
  - generate_pages.js
  - .github
  - .gitignore

# Коллекция товаров
collections:
  products:
    output: true
    permalink: /:collection/:path/

# Настройки по умолчанию для товаров
defaults:
  - scope:
      path: "_products/*.md"
    values:
      layout: "product"
