title: ENKA Electronics
description: ENKA Electronics - ხარისხიანი ტექნიკა საქართველოში უფასო მიტანით და ადგილზე გადახდით.

url: "https://enkaelectronics.com.ge"
baseurl: ""
encoding: utf-8
facebook_pixel_id: "1499689204986172"

# Включаем инкрементальную сборку по умолчанию
incremental: true

include: [_pages]

# Исключаем служебные файлы и папки из итогового билда
exclude:
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - generate_pages.js
  - assets/css/input.css
  - .github
  - .gitignore
  - .git
  - .bundle
  - .jekyll-cache

# Коллекция товаров
collections:
  products:
    output: true
    permalink: /product/:title/

# Настройки по умолчанию для коллекции товаров
defaults:
  - scope:
      path: ""
      type: "products"
    values:
      layout: "product"

# Плагины
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Настройки для sitemap
sitemap:
  filename: sitemap.xml

# Локализация
lang: "ka"
locale: "ka_GE"
