name: Replace secrets

on:
  push:
    branches: [ main ]

jobs:
  replace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Replace GH_PAT in HTML
        run: |
          sed -i "s|___GH_PAT___|${{ secrets.GH_PAT }}|g" smartscale/index.html
      
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add smartscale/index.html
          git diff --staged --quiet || git commit -m "Replace GH_PAT"
          git push
